### ISSUE TITLE
Can you upload training scripts?

### ISSUE THREAD

**Issue by hwang1996** [jssprz/attentive-specialized-network-video-captioning#1]
Thanks for sharing your codes.

It seems that you did not upload the training codes, can you share them please? Thanks.

**Comment by jssprz** [comment]
Thanks for your interest in the method. 
We have not included the training script yet. You can find the training setup we used in the [pre-print](https://users.dcc.uchile.cl/~jeperez/media/2020/icpr_2020_AVSSN.pdf) version of the paper. 
Any questions about parameters, just ask.
