### ISSUE TITLE
Problems with downloading files

### ISSUE THREAD

**Issue by Johnzu-2019** [jssprz/attentive-specialized-network-video-captioning#2]
Hello, thank you very much for the code you provided, but I found that I could not download these two files:
MSR-VTT/corpus.pkl
MSR-VTT/captioning_chkpt_15.pt

**Comment by jssprz** [comment]
Sorry, the files are incorrectly named on the server. Now the links work!

**Comment by jssprz** [comment]
Could you download the files?
If you can't, you will need to clone the repository again.
