### ISSUE TITLE
is there train_reference.txt for both MSRVTT and MSVD?

### ISSUE THREAD

**Issue by Mollylulu** [jssprz/attentive-specialized-network-video-captioning#3]

**Comment by Fred199683** [comment]
hello, I am wondering where to get the paper"Attentive Visual Semantic Specialized Network for video caption",have u read the paper?

**Comment by jssprz** [comment]
This is a [pre-print](https://users.dcc.uchile.cl/~jeperez/media/2020/icpr_2020_AVSSN.pdf) version of the paper to appear in the ICPR'20 Conference.

**Comment by jssprz** [comment]
All the information for training the models is stored and tokenized in the corpus.pkl files. We use the val_references.txt and test_references.tx files for computing the evaluation metrics only.
The content of these files is organized as follow:
0. train_data: captions and idxs of training videos in format [corpus_widxs, vidxs], where:
    - corpus_widxs is a list of lists with the index of words in the vocabulary
    - vidxs is a list of indexes of video features in the features file
1. val_data: same format of train_data.
2. test_data: same format of train_data.
3. vocabulary: in format {'word': count}.
4. idx2word: is the vocabulary in format {idx: 'word'}.
5. word_embeddings: are the vectors of each word. The i-th row is the word vector of the i-th word in the vocabulary.

The URLs for downloading these files are:
https://s06.imfd.cl/04/github-data/AVSSN/MSVD/corpus.pkl  
https://s06.imfd.cl/04/github-data/AVSSN/MSR-VTT/corpus.pkl
