### ISSUE TITLE
Could u plz give a link to read ur paper "Attentive Visual Semantic Specialized Network for Video Captioning"

### ISSUE THREAD

**Issue by Fred199683** [jssprz/attentive-specialized-network-video-captioning#5]
I am very interested in ur work. But I can't find the original paper. Could you please share a link to read your paper"Attentive Visual Semantic Specialized Network for Video Captioning", Thanks a lot!

**Comment by jssprz** [comment]
Hello, we are grateful that you are interested in the job. You can read this pre-print version of the paper to appear in the ICPR'20 Conference.
